import { Job, JobType, Category } from './types';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'Soma Software',
    location: 'Phnom Penh, CM',
    salary: '$2,500 - $4,500',
    type: JobType.FULL_TIME,
    logo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=100&h=100&fit=crop',
    category: Category.DEVELOPMENT,
    postedAt: '2h ago',
    urgent: true,
    description: 'We are looking for a rockstar Frontend Engineer to join our core team. You will be responsible for building smooth user experiences using React and Framer Motion.',
  },
  {
    id: '2',
    title: 'Product Designer (UI/UX)',
    company: 'Vattanac Bank',
    location: 'Remote (Cambodia)',
    salary: '$1,800 - $3,200',
    type: JobType.REMOTE,
    logo: 'https://images.unsplash.com/photo-1572044162444-ad60f128bde2?w=100&h=100&fit=crop',
    category: Category.DESIGN,
    postedAt: '5h ago',
    urgent: false,
    description: 'Help us redefine banking in Cambodia. Join our design team to create the most intuitive financial tools in the region.',
  },
  {
    id: '3',
    title: 'Growth Marketing Lead',
    company: 'Nham24',
    location: 'Phnom Penh',
    salary: '$2,000 - $3,500',
    type: JobType.FULL_TIME,
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=100&h=100&fit=crop',
    category: Category.MARKETING,
    postedAt: '1d ago',
    urgent: true,
    description: 'Nham24 is scaling fast. We need a marketing expert who knows the local market and can drive user acquisition through creative campaigns.',
  },
  {
    id: '4',
    title: 'Customer Success Manager',
    company: 'Wing Bank',
    location: 'Siem Reap',
    salary: '$1,200 - $2,000',
    type: JobType.PART_TIME,
    logo: 'https://images.unsplash.com/photo-1549421263-60848344df4a?w=100&h=100&fit=crop',
    category: Category.CUSTOMER_SERVICE,
    postedAt: '2d ago',
    urgent: false,
    description: 'Ensure our customers in the cultural capital of Cambodia receive the best service possible. Fluent English and Khmer are required.',
  },
];
